flaskblog/posts/models.py
from flaskblog import db
from datetime import datetime

class Post(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text(), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    # Since user_id Column of User table is foreign key for Post table,
    # we can use post.author to access the owner / writer of the post.

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"

flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

class EditPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Update Post')

# We can use the same form class for both create new post route and update post route. 
# but I needed to change the submit button text.

flaskblog/main/routes.py
from flask import request, render_template, Blueprint
from flaskblog.posts.models import Post

main = Blueprint('main', __name__)

@main.route('/')
def home():
    page = request.args.get('page', 1, type=int) # Get the url atribute named 'page'(type int) if not found default will use. 
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5) # get the posts ordered by date. in descending order
    return render_template('home.html', posts=posts)

@main.route('/about')
def about():
    # TODO finish this route by adding a html template
    return render_template('about.html')

flaskblog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flaskblog import db
from flaskblog.posts.forms import PostForm, EditPostForm
from flaskblog.posts.models import Post
from flask_login import current_user, login_required


posts = Blueprint('posts', __name__)

@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('You post successfuly created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form)


@posts.route('/post/<int:post_id>', methods=['GET'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    # get_or_404 : if sqlalchemy can't find a post with given post_id it will retrun a 404 not found error page
    return render_template('post.html', title=post.title, post=post)

@posts.route('/post/<int:post_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = EditPostForm()

    if current_user != post.author:
        return abort(403)
        # if a user tries to edit a post from another user it will abort the connection with 404 (forbidden) error
        
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.title.data
        db.session.commit()
        flash('You post successfuly Updated!', 'success')
        return redirect(url_for('main.home'))
    form.title.data = post.title
    form.content.data = post.content
    return render_template('edit_post.html', title='Edit Post', form=form)
    
@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    
    if current_user != post.author:
        return abort(403)
    
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted successfuly!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort
from flaskblog import db, bcrypt
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, PasswordResetEmailForm, PasswordResetForm
from flaskblog.users.models import User
from flaskblog.posts.models import Post
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog.users.utils import save_picture, remove_picure, reset_email


# initiating the Blueprint Object
users = Blueprint('users', __name__)

@users.route('/login', methods=['GET', 'POST'])
def login():
	# if user is already loged in and authenticated they will redirect to home page
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
        
    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
        	# if a user exists with that email and their pasword hashes match, they will be loge in via flask_login's login_user function
            login_user(user, remember=form.remember.data)

			# if user got redirect to login route from some other route 
			# (if user tried to visit a route that is login required, flask will redirect them to login route) 
			# url parameter called 'next' will be added to url. it will contain the previous rotute that user came from
			# and when they successfuly loged in, they will redirected back to the route that they came
			# if there's no parameter called next in the url, they will redirect to home route
            next_page = request.args.get('next')
            if next_page:
                flash(f"Login successful!", "success")
                return redirect(next_page)
            else:
                flash(f"Login successful!", "success")
                return redirect(url_for('main.home'))
        else:
            flash(f"Login unsuccessful! Please check your email & password", "danger")
        
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))
    

@users.route('/register', methods=['GET', 'POST'])
def register():
	# if user is already loged in and authenticated they will redirect to home page
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
        
    form = RegistrationForm()
    if form.validate_on_submit():
    
    	# hashing the password that user enterd
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        
        # creting the user with given details and hashed password
        user = User(username=form.username.data, email=form.email.data, password=hashed_pw)
        
        # adding user to db and commiting changes
        db.session.add(user)
        db.session.commit()
        
        flash(f"Account has been created! you are now able to log in", "success")
        return redirect(url_for('users.login'))

    return render_template('register.html', title='Register Now', form=form)


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            file_name = save_picture(form.picture.data)
            remove_picure(current_user.image_file)
            # updating the image file 
            current_user.image_file = file_name
        
        # Updating the user details with given values
        current_user.username = form.username.data
        current_user.email = form.email.data
        
        # commiting all changes 
        db.session.commit()
        
        flash('Your account information has been updated succesfully', 'success')
        return redirect(url_for('users.account'))
        
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title="Account", image=image, form=form)


@users.route('/user/<string:username>/delete_account', methods=['POST'])
@login_required
def delete_account(username):
    user = User.query.filter_by(username=username).first_or_404()

    if current_user != user:
        abort(403)
    
    # delete all the posts from user
    stmt = Post.__table__.delete().where(Post.author == user)
    db.session.execute(stmt)
    logout_user()
    db.session.delete(user)
    db.session.commit()
    flash('Your account has been deleted successfully.', 'success')
    return redirect(url_for('main.home'))

@users.route('/user/<string:username>', methods=['GET'])
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404() # return 404 not found page if user not found for given username
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = PasswordResetEmailForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        reset_email(user)
        flash(f'Password Reqeust Email has been sent to {form.email.data}. Please check your inbox', 'success')
        return redirect(url_for('users.login'))

    return render_template('password_reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<string:token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_auth_token(token)
    if user is None:
        flash('Invalid or Expired token', 'danger')
        return redirect(url_for('users.reset_request'))

    form = PasswordResetForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pw
        db.session.commit()
        flash(f'Your Password has been updated. Now you can login', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html', title='Update Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html"%}

{% block body%}
    <h1>About Page</h1>
{% endblock %}

flaskblog/templates/account.html
{% extends "layout.html"%}

{% block body%}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
                <a class="btn btn-sm btn-warning" href="{{ url_for('users.user_posts', username=current_user.username) }}">My Posts</a>
                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModel">Delete Account</button>
            </div>
        </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Update Account Info</legend>
                <div class="form-group">
                    {{form.username.label(class="form-control-label") }}
                    
                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.username(class="form-control form-control-lg") }}
                    {% endif%}

                </div>
                <div class="form-group">
                    {{form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.email(class="form-control form-control-lg") }}
                    {% endif%}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}<br>
                    {{ form.picture(class="form-contorl-file") }}<br>
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

    <!-- Delete Modal -->
    <div class="modal fade" id="deleteModel" tabindex="-1" role="dialog" aria-labelledby="deleteModelLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModelLabel">Are you sure?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('users.delete_account', username=current_user.username) }}", method="POST">
                <input type="submit" value="Delete my account" class="btn btn-danger">
            </form>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}

{% block body %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create New Post</legend>
            <div class="form-group">
                {{form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.title(class="form-control form-control-lg") }}
                {% endif%}
            </div>
            <div class="form-group">
                {{form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.content(class="form-control form-control-lg") }}
                {% endif%}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock %}

flaskblog/templates/edit_post.html
{% extends 'layout.html' %}

{% block body %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create New Post</legend>
            <div class="form-group">
                {{form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.title(class="form-control form-control-lg") }}
                {% endif%}
            </div>
            <div class="form-group">
                {{form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.content(class="form-control form-control-lg") }}
                {% endif%}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    </div>
{% endblock %}

flaskblog/templates/home.html
{% extends "layout.html" %}

{% block body %}
    {% for post in posts.items %}
        <article class="media content-section">
            <div class="media-body">
            <div class="article-metadata">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            </div>
        </article> 
    {% endfor %}
    
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
            <li class="page-item active"><a class="page-link" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
        </ul>   
    </nav>

{% endblock %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"
      href="https://bootswatch.com/4/united/bootstrap.min.css"
    -->
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css')}}" type="text/css">
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header" >
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
            <a class="navbar-brand mr-4" href="/">Flask Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
                <!-- Navbar Right Side -->
                {% if current_user.is_authenticated%}
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                  </div>
                {% else %}
                <div class="navbar-nav">
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                </div>
                {% endif %}
            </div>
            </div>
        </nav>
    </header>
    
    <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
                {% endfor %}
              {% endif%}
            {% endwith %}
            {% block body %}{% endblock %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.</p>
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
            </div>
          </div>
        </div>
    </main>

    <!--Bootstrap JS-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}

{% block body %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login Now</legend>
                <div class="form-group">
                    {{form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.email(class="form-control form-control-lg") }}
                    {% endif%}
                </div>
                <div class="form-group">
                    {{form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{form.password(class="form-control form-control-lg") }}
                    {% endif%}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">Don't have an account? <a href="{{ url_for('users.register') }}" class="ml-2">Sign up</a></small>
    </div>
{% endblock %}

flaskblog/templates/password_reset_request.html
{% extends 'layout.html' %}

{% block body %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Send Password Reset Email</legend>
            <div class="form-group">
                {{form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{form.email(class="form-control form-control-lg") }}
                {% endif%}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock %}

flaskblog/templates/post.html
{% extends 'layout.html' %}

{% block body %}
<article class="media content-section">
    <div class="media-body">
    <div class="article-metadata">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
    </div>
    <h2>{{ post.title }}</h2>
    <p class="article-content">{{ post.content }}</p>
    <div>
    {% if current_user.id == post.author.id %}
      <a href="{{ url_for('posts.edit_post', post_id=post.id) }}" class="btn btn-primary btn-sm">Edit Post</a>
      <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModel">Delete Post</button>
    </div>
    {% endif%}
 
</article> 

<!-- Delete Modal -->
<div class="modal fade" id="deleteModel" tabindex="-1" role="dialog" aria-labelledby="deleteModelLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModelLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}", method="POST">
              <input type="submit" value="Delete" class="btn btn-danger">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

flaskblog/templates/user_posts.html
{% extends 'layout.html' %}

{% block body %}
    <h2 class="mb-2">Posts of <span class="text-primary">{{ user.username }}</span> ({{ posts.total }})</h2>
    {% for post in posts.items %}
    <article class="media content-section">
        <div class="media-body">
        <div class="article-metadata">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
        </div>
    </article> 
    {% endfor %}

    <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
        {% if posts.page == page_num %}
        <li class="page-item active"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
        {% endif %}
    {% else %}
        ...
    {% endif %}
    {% endfor %}
    </ul>   
    </nav>
{% endblock %}